INSERT INTO categories (slug, name, parent_label, audience, sort_order) VALUES
('sale-rainy-day-curation','Rainy Day Curation','Sale','women',1),
('women-ethnic-salwar-kameez','Salwar Kameez','Women / Ethnic Wear','women',10),
('women-ethnic-kameez','Kameez','Women / Ethnic Wear','women',11),
('women-ethnic-saree','Saree','Women / Ethnic Wear','women',12),
('women-ethnic-tunics','Tunics','Women / Ethnic Wear','women',13),
('women-bottom-wear','Bottom Wear','Women','women',14),
('women-footwear-jutties','Jutties','Women / Footwear','women',20),
('women-footwear-mules','Mules','Women / Footwear','women',21),
('women-footwear-sandals','Sandals','Women / Footwear','women',22),
('women-footwear-slippers','Slippers','Women / Footwear','women',23),
('women-fusion-tunic','Tunic','Women / Western & Fusion','women',30),
('women-fusion-tunic-with-shrug','Tunic With Shrug','Women / Western & Fusion','women',31),
('women-fusion-long-tunic','Long Tunic','Women / Western & Fusion','women',32),
('women-fusion-top-bottom-set','Top And Bottom Set','Women / Western & Fusion','women',33),
('women-fusion-koti','Koti','Women / Western & Fusion','women',34),
('women-fusion-shirt','Women''s Shirt','Women / Western & Fusion','women',35),
('women-fusion-gown','Gown','Women / Western & Fusion','women',36),
('women-fusion-tops','Tops & T-Shirts','Women / Western & Fusion','women',37),
('women-fusion-shrug','Shrug','Women / Western & Fusion','women',38),
('women-fusion-maxi','Maxi','Women / Western & Fusion','women',39),
('women-accessory-handbag','Hand Bag','Women / Accessories','women',40),
('women-accessory-earring','Earring','Women / Accessories','women',41),
('women-accessory-ring','Finger Ring','Women / Accessories','women',42),
('women-accessory-hair-clip','Hair Clip','Women / Accessories','women',43),
('women-accessory-bangles','Bangles','Women / Accessories','women',44),
('women-accessory-socks','Socks','Women / Accessories','women',45),
('women-accessory-bracelet','Bracelet','Women / Accessories','women',46),
('women-accessory-jewelry-box','Jewelry Box','Women / Accessories','women',47),
('women-accessory-anklet','Anklet','Women / Accessories','women',48),
('women-accessory-brooch','Brooch','Women / Accessories','women',49),
('women-accessory-necklace','Necklace','Women / Accessories','women',50),
('women-accessory-headband','Headband And Scrunchies','Women / Accessories','women',51),
('women-accessory-dupatta','Dupatta','Women / Accessories','women',52),
('women-accessory-scarf','Scarf','Women / Accessories','women',53),
('women-abaya-set','Abaya Set','Women / Abaya & Hijab','women',60),
('women-hijab','Hijab','Women / Abaya & Hijab','women',61),
('women-abaya','Abaya','Women / Abaya & Hijab','women',62),
('women-beauty-accessories','Beauty Accessories','Women','women',63),
('women-yoga','Yoga Collection','Women','women',64),
('women-9-to-9','9 To 9','Women','women',65),
('women-sleepwear','Sleepwear','Women','women',66),
('women-daily-towel','Ethnic Bath Towel','Women / Daily Life','women',70),
('women-daily-water-bottle','Water Bottle','Women / Daily Life','women',71),
('women-daily-umbrella','Umbrella','Women / Daily Life','women',72),
('women-daily-raincoat','Raincoat','Women / Daily Life','women',73),
('teen-boys-polo','Polo','Teens / Boys Clothing','kids',80),
('teen-boys-tshirt','T-Shirt','Teens / Boys Clothing','kids',81),
('teen-boys-casual-shirt','Casual Shirt','Teens / Boys Clothing','kids',82),
('teen-boys-panjabi','Panjabi','Teens / Boys Clothing','kids',83),
('teen-girls-salwar-kameez','Salwar Kameez','Teens / Girls Clothing','kids',90),
('teen-girls-kameez','Kameez','Teens / Girls Clothing','kids',91),
('teen-girls-tunics','Tunics','Teens / Girls Clothing','kids',92),
('teen-girls-shirt','Shirt','Teens / Girls Clothing','kids',93),
('teen-girls-tops','Tops','Teens / Girls Clothing','kids',94),
('teen-girls-tshirt','T-Shirt','Teens / Girls Clothing','kids',95),
('teen-girls-jumpsuit','Jump Suit','Teens / Girls Clothing','kids',96),
('teen-girls-bottom-wear','Bottom Wear','Teens / Girls Clothing','kids',97),
('kids-boys-polo','Polo','Kids / Boys Clothing','kids',100),
('kids-boys-tshirt','T-Shirt','Kids / Boys Clothing','kids',101),
('kids-boys-casual-shirt','Casual Shirt','Kids / Boys Clothing','kids',102),
('kids-boys-panjabi','Panjabi','Kids / Boys Clothing','kids',103),
('kids-boys-pajama','Pajama','Kids / Boys Clothing','kids',104),
('kids-boys-quarter-pants','3 Quarter Pants','Kids / Boys Clothing','kids',105),
('kids-boys-bottoms','Bottoms','Kids / Boys Clothing','kids',106),
('kids-boys-kabli-set','Kabli Set','Kids / Boys Clothing','kids',107),
('kids-boys-panjabi-set','Panjabi Set','Kids / Boys Clothing','kids',108),
('kids-girls-frocks','Frocks','Kids / Girls Clothing','kids',110),
('kids-girls-tunics','Tunics','Kids / Girls Clothing','kids',111),
('kids-girls-salwar-kameez','Salwar Kameez','Kids / Girls Clothing','kids',112),
('kids-girls-ghagra-choli','Ghagra Choli','Kids / Girls Clothing','kids',113),
('kids-girls-clothing-sets','Clothing Sets','Kids / Girls Clothing','kids',114),
('kids-girls-leggings','Leggings','Kids / Girls Clothing','kids',115),
('kids-girls-palazzo','Palazzo','Kids / Girls Clothing','kids',116),
('kids-girls-innerwear','Innerwear','Kids / Girls Clothing','kids',117),
('kids-girls-bag','Bag','Kids / Girls Clothing','kids',118),
('kids-girls-accessories','Accessories','Kids / Girls Clothing','kids',119),
('kids-girls-footwear','Footwear','Kids / Girls Clothing','kids',120),
('newborn-boys-shirt-pant','Boy''s Shirt Pant Set','New Born / Boys','kids',130),
('newborn-boys-nima','Boy''s Nima Set','New Born / Boys','kids',131),
('newborn-boys-panjabi','Boy''s Panjabi','New Born / Boys','kids',132),
('newborn-boys-polo','Boy''s Polo','New Born / Boys','kids',133),
('newborn-boys-tshirt','Boy''s T-Shirt','New Born / Boys','kids',134),
('newborn-boys-fotua-pant','Boy''s Fotua Pant Set','New Born / Boys','kids',135),
('newborn-girls-frock','Girl''s Frock','New Born / Girls','kids',140),
('newborn-girls-skirt-top','Girl''s Skirt-Tops Set','New Born / Girls','kids',141),
('newborn-girls-ghagra','Girl''s Ghagra Choli','New Born / Girls','kids',142),
('newborn-girls-nima','Girl''s Nima Set','New Born / Girls','kids',143),
('newborn-girls-salwar-kameez','Girl''s Salwar Kameez','New Born / Girls','kids',144),
('newborn-girls-bottom-top','Girl''s Bottom-Tops Set','New Born / Girls','kids',145),
('mini-me-father-son','Father-Son','Kids / Mini-Me Collection','kids',150),
('mini-me-mother-daughter','Mother-Daughter','Kids / Mini-Me Collection','kids',151),
('mini-me-matching','Matching','Kids / Mini-Me Collection','kids',152),
('kids-daily-towel','Ethnic Bath Towel','Kids / Daily Life','kids',160),
('kids-daily-water-bottle','Water Bottle','Kids / Daily Life','kids',161),
('kids-daily-backpack','Kids Backpack','Kids / Daily Life','kids',162),
('kids-daily-umbrella','Umbrella','Kids / Daily Life','kids',163),
('kids-daily-raincoat','Kids Raincoat','Kids / Daily Life','kids',164),
('kids-daily-school-shoe','School Shoe','Kids / Daily Life','kids',165),
('kids-daily-socks','Socks','Kids / Daily Life','kids',166),
('nargisus-salwar-kameez','Salwar Kameez','Nargisus / Ethnic Wear','women',170),
('nargisus-kameez','Kameez','Nargisus / Ethnic Wear','women',171),
('nargisus-tunic','Tunic','Nargisus / Western & Fusion','women',172)
ON CONFLICT(slug) DO UPDATE SET name=excluded.name, parent_label=excluded.parent_label, audience=excluded.audience, sort_order=excluded.sort_order;
