name = "zayaans-signature-api"
main = "worker.ts"
compatibility_date = "2025-09-01"
account_id = "0b1d4447f765e7fd26243f6a462d728a"

[vars]
ALLOWED_ORIGIN = "https://bayzed123.github.io"

[[d1_databases]]
binding = "NEWSLETTER"
database_name = "zayaans-signature-newsletter"
database_id = "ad1c0c18-5711-4ede-b15e-be289963875d"
